### ISSUE TITLE
Test Runner mismatch between JSON and on-page reporting

### ISSUE THREAD

**Issue by brettz9** [w3c/wpt-tools#152]
Within IndexedDB tests (on Chrome 55.0.2883.87 m), I'm getting the following result for one of the test files:

```json
{
      "test": "/indexeddb/idbcursor-continueprimarykey-exception-order.htm",
      "subtests": [],
      "status": "TIMEOUT",
      "message": ""
    }
```

The timeout count also includes it correctly.

However, the "Status" column in the "Test Details" output on the test page for this file is showing as "NOTRUN".

**Comment by brettz9** [comment]
Also, while the test count at `http://web-platform.test:8000/indexeddb//idbcursor-continueprimarykey-exception-order.htm` also indicates the presence of 13 tests (in Chrome, besides the timeout, the other 12 are failing), the passing vs. total count on the aggregate page only shows 0/1 for this test.

(Also problematic I think, on the individual test, the "Harness Status" is listed as "Error" even though on the aggregate page, the Error count is 0.)

Even stranger, while `http://web-platform.test:8000/indexeddb//idbcursor-continueprimarykey-exceptions.htm`  shows 3 total tests (3 of which are failing in Chrome), this page does not show up at all in the results on the aggregate page for `/indexeddb` (though all other tests do).

**Comment by jgraham** [comment]
With `idbcursor-continueprimarykey-exception-order.htm` it seems like the test errors in Chrome in a way that causes no tests to be run and a timeout. The timeout is correctly reported, and the runner sets the subtest status to `NOTRUN` because it finds that the number of `NOTRUN` tests is equal to the total number of tests (0). That's a little confusing, but it's not obviously doing anything wrong.

I also see `idbcursor-continueprimarykey-exceptions.htm` in the results details and in the json file.

**Comment by inexorabletash** [comment]
`continuePrimaryKey()` is not available in chrome stable; is it just that the test is written in such a way that it times out rather than failing if not present?

cc: @pwnall

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7203; please continue all discussion there.
